export const SEED_OPPORTUNITIES = [
  {
    id: 'OPP-001',
    title: 'Plumber needed',
    category: 'Trades',
    skills: ['plumbing'],
    location: 'Lagos',
    language: 'english',
    pay: 15000,
    payFrequency: 'per job',
    distance: '2.1 km',
    duration: '1 day',
    postedBy: 'HomeFixNG',
  },
  {
    id: 'OPP-002',
    title: 'Delivery rider',
    category: 'Logistics',
    skills: ['riding', 'navigation'],
    location: 'Abuja',
    language: 'english',
    pay: 8000,
    payFrequency: 'per day',
    distance: '4.5 km',
    duration: '3 months',
    postedBy: 'QuickDrop',
  },
  {
    id: 'OPP-003',
    title: 'Phone repair technician',
    category: 'Tech',
    skills: ['electronics', 'repair'],
    location: 'Lagos',
    language: 'yoruba',
    pay: 20000,
    payFrequency: 'per week',
    distance: '1.8 km',
    duration: '6 months',
    postedBy: 'GadgetHub',
  },
  {
    id: 'OPP-004',
    title: 'Market sales agent',
    category: 'Sales',
    skills: ['sales', 'negotiation'],
    location: 'Kano',
    language: 'hausa',
    pay: 12000,
    payFrequency: 'per week',
    distance: '3.2 km',
    duration: '3 months',
    postedBy: 'TradeLink',
  },
  {
    id: 'OPP-005',
    title: 'Seamstress/tailor',
    category: 'Fashion',
    skills: ['sewing', 'tailoring'],
    location: 'Lagos',
    language: 'yoruba',
    pay: 18000,
    payFrequency: 'per week',
    distance: '0.9 km',
    duration: '6 months',
    postedBy: 'StitchCo',
  },
]
